"""Ledger and audit trail for the INR facilitator — SQLite locally, Postgres
in production, behind the shim in db.py.

Every state change a payment goes through is written here, and every write also
emits a structured JSON line to stdout. The ledger is the answer to the
question a publisher will actually ask — *which agent owes me what, and did it
get paid?* — so it is deliberately the most boring, most explicit code in the
project.

Six tables:

    agents         an agent's registered Ed25519 public key
    offers         a quoted price, signed and time-limited
    batches        one real Razorpay charge covering many commitments
    commitments    an agent's accepted offer — a debt, not yet money
    events         append-only log of everything that happened
    webhook_events Razorpay callbacks we have already processed

(`batches` is declared before `commitments` because `commitments.batch_id`
references it — SQLite resolves foreign keys lazily and does not care about
declaration order, but Postgres checks at `CREATE TABLE` time and errors if
the referenced table does not exist yet.)

The offer -> commitment -> batch progression is the whole idea. A ₹5 API call
becomes a commitment instantly (cheap, no gateway involved), and rupees move
later when many commitments are charged together.

COMMITTED IS NOT COLLECTED
--------------------------
Two different questions live in this schema and it is worth being precise
about which column answers which, because conflating them is how a payments
ledger ends up overstating revenue:

  * `commitments.status = 'settled'` means *this debt has been assigned to a
    batch*. It is no longer separately chargeable and will not be
    double-billed. It does **not** mean anyone has paid.
  * `batches.status = 'paid'` means Razorpay told us — over a signed webhook
    (see webhooks.py) — that money actually arrived.

A Payment Link that was created is an invoice, not a receipt. Until the
webhook lands, the honest description of a batch is "billed, awaiting
payment", which is why `daily_summary` reports `committedPaise` and
`collectedPaise` as separate figures rather than one number labelled
"revenue".

Money is stored as INTEGER paise throughout. Never floats — a float would
silently lose precision on rupee arithmetic and there is no reason to risk it.
"""

from __future__ import annotations

import json
import os
import re
import sys
import threading
from collections.abc import Iterator, Mapping
from contextlib import contextmanager
from datetime import UTC, datetime
from typing import Any

import db

# Serialises writes within one process. Correctness does not depend on this —
# `create_commitment`'s atomic conditional UPDATE (see below) is what actually
# prevents a double-charge, and that holds under Postgres across separate
# processes regardless. This lock only avoids SQLite's "database is locked"
# noise under FastAPI's threadpool, and costs nothing worth special-casing
# away for Postgres, so it applies uniformly to both.
_WRITE_LOCK = threading.Lock()

DEFAULT_DB_PATH = os.getenv("LEDGER_DB_PATH", "./data/ledger.db")


# Matches the `user:password@` portion of any connection URL. Database driver
# errors quote the DSN they failed on more often than you would like — psycopg
# does it on several connection failures — so any driver message that escapes
# this module has to be scrubbed first, not merely assumed to be clean.
_DSN_CREDENTIALS_RE = re.compile(r"://[^\s/@]+:[^\s/@]+@")


def redact_credentials(text: str) -> str:
    """Strips `user:password@` out of any connection URL in `text`.

    Keeps the scheme and host, which are what make an error diagnosable, and
    drops the part that must never reach a log line or an HTTP response.

    Args:
        text: Arbitrary message text, typically a driver exception.

    Returns:
        The same text with credentials replaced.
    """
    return _DSN_CREDENTIALS_RE.sub("://<redacted>@", text)


def utc_now() -> str:
    """Current time as an ISO-8601 UTC string.

    One timestamp format everywhere, so ledger rows sort lexicographically and
    the reporting script does not need a date parser.
    """
    return datetime.now(UTC).isoformat(timespec="seconds").replace("+00:00", "Z")


def today_utc() -> str:
    """Current UTC date as YYYY-MM-DD — the batching key."""
    return datetime.now(UTC).strftime("%Y-%m-%d")


def _events_id_column(dialect: str) -> str:
    """The one line of DDL that actually differs between engines.

    Every other table, column, and constraint below is identical SQL in both
    SQLite and Postgres — this auto-incrementing primary key is the single
    exception, so it is the only thing parameterised rather than duplicating
    the whole schema for one line's difference.
    """
    if dialect == "postgres":
        return "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "id INTEGER PRIMARY KEY AUTOINCREMENT"


def schema_sql(dialect: str) -> str:
    """The full schema, for either engine.

    Args:
        dialect: "sqlite" or "postgres".
    """
    return f"""
-- One row per agent that has registered a signing key. Holds only the
-- *public* half: the facilitator can verify an agent's commitments and can
-- never produce one, which is the entire point of moving off a shared HMAC
-- secret (see payment_verifier.py).
CREATE TABLE IF NOT EXISTS agents (
    agent_id      TEXT PRIMARY KEY,
    -- base64 of the raw 32-byte Ed25519 public key.
    public_key    TEXT NOT NULL,
    algorithm     TEXT NOT NULL,
    registered_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS offers (
    offer_id      TEXT PRIMARY KEY,
    agent_id      TEXT NOT NULL,
    resource_id   TEXT NOT NULL,
    resource_url  TEXT,
    amount_paise  INTEGER NOT NULL,
    asset         TEXT NOT NULL,
    scheme        TEXT NOT NULL,
    network       TEXT NOT NULL,
    pay_to        TEXT NOT NULL,
    nonce         TEXT NOT NULL,
    signature     TEXT NOT NULL,
    issued_at     TEXT NOT NULL,
    expires_at    TEXT NOT NULL,
    -- open: quoted, not yet spent. consumed: turned into a commitment.
    status        TEXT NOT NULL DEFAULT 'open'
);

CREATE TABLE IF NOT EXISTS batches (
    batch_id            TEXT PRIMARY KEY,
    agent_id            TEXT NOT NULL,
    settle_date         TEXT NOT NULL,
    created_at          TEXT NOT NULL,
    commitment_count    INTEGER NOT NULL,
    total_paise         INTEGER NOT NULL,
    -- What Razorpay gave us back. Null in dry-run.
    payment_link_id     TEXT,
    payment_link_url    TEXT,
    -- created | paid | expired | cancelled | failed | dry_run
    --
    -- `created` means an invoice exists, NOT that money arrived. Only the
    -- signed Razorpay webhook moves a batch to `paid` (see webhooks.py).
    status              TEXT NOT NULL,
    razorpay_mode       TEXT NOT NULL,
    error_message       TEXT,
    -- Filled in by the webhook, not by the settlement run that created the
    -- link. Null until Razorpay confirms payment.
    paid_at             TEXT,
    amount_paid_paise   INTEGER,
    razorpay_payment_id TEXT
);

CREATE TABLE IF NOT EXISTS commitments (
    commitment_id TEXT PRIMARY KEY,
    -- One commitment per offer, enforced by the database rather than by
    -- application logic. This is what makes double-charging structurally
    -- impossible rather than merely unlikely.
    offer_id      TEXT NOT NULL UNIQUE,
    agent_id      TEXT NOT NULL,
    resource_id   TEXT NOT NULL,
    amount_paise  INTEGER NOT NULL,
    asset         TEXT NOT NULL,
    created_at    TEXT NOT NULL,
    settle_date   TEXT NOT NULL,
    -- deferred: awaiting batch. per_request: charged immediately.
    mode          TEXT NOT NULL,
    -- pending | settled | failed
    status        TEXT NOT NULL DEFAULT 'pending',
    batch_id      TEXT,
    FOREIGN KEY (offer_id) REFERENCES offers (offer_id),
    FOREIGN KEY (batch_id) REFERENCES batches (batch_id)
);

-- Append-only. Nothing in this table is ever updated or deleted; it is the
-- audit trail you would hand an auditor or replay to reconstruct a day.
CREATE TABLE IF NOT EXISTS events (
    {_events_id_column(dialect)},
    ts           TEXT NOT NULL,
    event        TEXT NOT NULL,
    agent_id     TEXT,
    resource_id  TEXT,
    amount_paise INTEGER,
    status       TEXT,
    detail       TEXT
);

-- Razorpay retries a webhook until it gets a 2xx, so the same event will
-- arrive more than once as a matter of course — not as an edge case. The
-- primary key is the dedupe guard: processing claims the key with an INSERT
-- first, and a duplicate delivery loses that INSERT and returns early
-- without touching a batch. Same discipline as `commitments.offer_id`:
-- exactly-once is enforced by a database constraint, not by application
-- logic remembering to check.
CREATE TABLE IF NOT EXISTS webhook_events (
    dedupe_key      TEXT PRIMARY KEY,
    event           TEXT NOT NULL,
    received_at     TEXT NOT NULL,
    payment_link_id TEXT,
    -- claimed | applied | ignored | unknown_link
    outcome         TEXT NOT NULL,
    detail          TEXT
);

CREATE INDEX IF NOT EXISTS idx_commitments_settlement
    ON commitments (status, agent_id, settle_date);
CREATE INDEX IF NOT EXISTS idx_events_ts ON events (ts);
CREATE INDEX IF NOT EXISTS idx_batches_payment_link ON batches (payment_link_id);
"""


class Ledger:
    """The facilitator's book of record — SQLite locally, Postgres in production.

    Args:
        dsn: A SQLite file path, or a `postgres://`/`postgresql://` connection
            URL. `db.dialect_for` decides which from the prefix.

    Schema bootstrap differs by engine. SQLite always runs `CREATE TABLE IF
    NOT EXISTS` on construction, as it always has — cheap, and a demo file
    that does not exist yet is the common case. Postgres does not, by
    default: schema changes on a shared production database belong in a
    migration applied deliberately (see `facilitator/migrations/001_init.sql`),
    not as a side effect of importing this module on every cold start. Set
    `LEDGER_AUTO_MIGRATE=1` to bootstrap a Postgres schema automatically
    anyway — used by CI, where the test database starts genuinely empty and
    there is no one to run a migration by hand.
    """

    def __init__(self, dsn: str = DEFAULT_DB_PATH) -> None:
        self.dsn = dsn
        self.dialect = db.dialect_for(dsn)

        if self.dialect == "sqlite":
            self.db_path = dsn
            parent = os.path.dirname(os.path.abspath(dsn))
            os.makedirs(parent, exist_ok=True)
            self._init_schema()
        else:
            self.db_path = None
            if os.getenv("LEDGER_AUTO_MIGRATE", "").strip().lower() in ("1", "true", "yes"):
                self._init_schema()

    @contextmanager
    def _connect(self) -> Iterator[db.Conn]:
        """Yields a connection, committing on success and rolling back on error."""
        with db.connect(self.dsn, self.dialect) as conn:
            yield conn

    def _init_schema(self) -> None:
        with _WRITE_LOCK, self._connect() as conn:
            conn.executescript(schema_sql(self.dialect))

    # -- audit -------------------------------------------------------------

    def log_event(
        self,
        event: str,
        *,
        agent_id: str | None = None,
        resource_id: str | None = None,
        amount_paise: int | None = None,
        status: str | None = None,
        **detail: Any,
    ) -> None:
        """Records one thing that happened, to both the ledger and stdout.

        Writing to two places on purpose: the table is queryable after the
        fact, and the stdout line is what you watch during a live demo. A
        rejected payment always goes through here with its reason — nothing in
        this service fails silently.

        Args:
            event: Machine-readable event name, e.g. "payment_verified".
            agent_id: Which agent this concerns.
            resource_id: Which resource this concerns.
            amount_paise: Money involved, in paise.
            status: Outcome marker, e.g. "ok" or "rejected".
            **detail: Anything else worth keeping; stored as JSON.
        """
        ts = utc_now()
        detail_json = json.dumps(detail, sort_keys=True, default=str) if detail else None

        with _WRITE_LOCK, self._connect() as conn:
            conn.execute(
                "INSERT INTO events"
                " (ts, event, agent_id, resource_id, amount_paise, status, detail)"
                " VALUES (?, ?, ?, ?, ?, ?, ?)",
                (ts, event, agent_id, resource_id, amount_paise, status, detail_json),
            )

        line = {
            "ts": ts,
            "service": "facilitator",
            "event": event,
            **({"agentId": agent_id} if agent_id else {}),
            **({"resourceId": resource_id} if resource_id else {}),
            **({"amountPaise": amount_paise} if amount_paise is not None else {}),
            **({"status": status} if status else {}),
            **detail,
        }
        print(json.dumps(line, sort_keys=True, default=str), file=sys.stdout, flush=True)

    def check_connection(self) -> tuple[bool, str]:
        """Whether the ledger is reachable right now.

        `SELECT 1` — a round trip that touches no table, so it reports on the
        connection rather than on whether a migration has been applied.

        Never raises. A health check that throws is a health check that turns
        one outage into two, and the caller wants a status to report rather
        than an exception to handle.

        Returns:
            `(ok, detail)` — detail names the failure when ok is False, with
            connection-string credentials scrubbed. Drivers quote the DSN they
            failed on, and this string is returned over HTTP by `/health`.
        """
        try:
            with self._connect() as conn:
                conn.execute("SELECT 1")
        except Exception as exc:  # noqa: BLE001 - reported to the caller, never raised
            return False, redact_credentials(f"{type(exc).__name__}: {str(exc)[:200]}")
        return True, "connected"

    # -- agent keys --------------------------------------------------------

    def register_agent(self, *, agent_id: str, public_key: str, algorithm: str) -> dict:
        """Records an agent's public signing key, first-registration-wins.

        Trust-on-first-use, and worth being explicit that this is a real
        limitation rather than a rounding error: the first caller to claim an
        agent id owns it, because there is nothing else here to bind that id
        to. A production facilitator would issue the key at onboarding
        alongside the merchant account it settles into, so the key is
        vouched-for rather than merely first.

        What TOFU *does* buy, and the reason it is worth having over a shared
        secret even so: once an id is claimed, no one else can spend as it,
        and the facilitator itself cannot forge its commitments either. The
        rebinding attempt is refused rather than silently overwriting, which
        is what stops key rotation from doubling as account takeover.

        Args:
            agent_id: Identity being registered.
            public_key: Base64 of the raw Ed25519 public key.
            algorithm: Signature algorithm, currently always "ed25519".

        Returns:
            `{"agentId", "publicKey", "algorithm", "registeredAt", "created"}`.
            `created` is False when this was an idempotent re-registration of
            the identical key.

        Raises:
            ValueError: If the id is already bound to a *different* key.
        """
        registered_at = utc_now()

        with _WRITE_LOCK, self._connect() as conn:
            # `ON CONFLICT DO NOTHING` rather than catching a unique violation,
            # for a dialect reason worth stating because SQLite hides it
            # completely: in Postgres a failed statement aborts the entire
            # transaction, and every subsequent command on that connection
            # fails with InFailedSqlTransaction until it is rolled back. So the
            # obvious try/except INSERT, then SELECT to see what is already
            # there cannot work — the recovery read is itself refused. SQLite
            # has no such rule and passes it happily, which is exactly why the
            # suite runs against both engines.
            #
            # This is also simply better: one statement does the claim, so
            # there is no read-then-write gap, the same reasoning as
            # `create_commitment` below.
            inserted = conn.execute(
                "INSERT INTO agents (agent_id, public_key, algorithm, registered_at)"
                " VALUES (?, ?, ?, ?) ON CONFLICT (agent_id) DO NOTHING",
                (agent_id, public_key, algorithm, registered_at),
            )

            if inserted.rowcount == 0:
                existing = conn.execute(
                    "SELECT * FROM agents WHERE agent_id = ?", (agent_id,)
                ).fetchone()
                # Re-registering the same key is a no-op, so an agent that
                # restarts and re-announces itself does not need to care
                # whether it has registered before.
                if existing is not None and existing["public_key"] == public_key:
                    return {
                        "agentId": agent_id,
                        "publicKey": existing["public_key"],
                        "algorithm": existing["algorithm"],
                        "registeredAt": existing["registered_at"],
                        "created": False,
                    }
                raise ValueError(
                    f"agent {agent_id} is already registered with a different public key"
                )

        return {
            "agentId": agent_id,
            "publicKey": public_key,
            "algorithm": algorithm,
            "registeredAt": registered_at,
            "created": True,
        }

    def get_agent(self, agent_id: str) -> Mapping[str, Any] | None:
        """Looks up an agent's registered key, or None if it has never registered."""
        with self._connect() as conn:
            return conn.execute(
                "SELECT * FROM agents WHERE agent_id = ?", (agent_id,)
            ).fetchone()

    # -- offers ------------------------------------------------------------

    def insert_offer(self, offer: dict, signature: str) -> None:
        """Stores a freshly quoted offer.

        Args:
            offer: The offer body that was signed.
            signature: HMAC over that body.
        """
        with _WRITE_LOCK, self._connect() as conn:
            conn.execute(
                "INSERT INTO offers (offer_id, agent_id, resource_id, resource_url, amount_paise,"
                " asset, scheme, network, pay_to, nonce, signature, issued_at, expires_at, status)"
                " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'open')",
                (
                    offer["offerId"],
                    offer["agentId"],
                    offer["resourceId"],
                    offer.get("resourceUrl"),
                    int(offer["amountPaise"]),
                    offer["asset"],
                    offer["scheme"],
                    offer["network"],
                    offer["payTo"],
                    offer["nonce"],
                    signature,
                    offer["issuedAt"],
                    offer["expiresAt"],
                ),
            )

    def get_offer(self, offer_id: str) -> Mapping[str, Any] | None:
        """Looks up one offer, or None."""
        with self._connect() as conn:
            cur = conn.execute("SELECT * FROM offers WHERE offer_id = ?", (offer_id,))
            return cur.fetchone()

    # -- commitments -------------------------------------------------------

    def get_commitment_by_offer(self, offer_id: str) -> Mapping[str, Any] | None:
        """Finds the commitment an offer already produced, if any.

        Used to make settlement idempotent: a retried /settle returns the
        original commitment rather than creating a second debt.
        """
        with self._connect() as conn:
            cur = conn.execute("SELECT * FROM commitments WHERE offer_id = ?", (offer_id,))
            return cur.fetchone()

    def create_commitment(
        self,
        *,
        commitment_id: str,
        offer_id: str,
        agent_id: str,
        resource_id: str,
        amount_paise: int,
        asset: str,
        mode: str,
        settle_date: str | None = None,
    ) -> dict:
        """Turns an open offer into a commitment, atomically.

        "Atomically" here does not mean "inside one transaction" — a
        transaction alone does not prevent two concurrent callers both
        reading `status = 'open'` before either has written, and both then
        proceeding to insert a commitment. It means the offer is claimed with
        a single conditional UPDATE:

            UPDATE offers SET status = 'consumed' WHERE offer_id = ? AND status = 'open'

        `WHERE status = 'open'` takes a row lock in both engines, and only one
        concurrent transaction can ever observe `rowcount == 1` — the other
        sees `0` and takes the "already consumed" branch below. There is no
        read-then-write gap to lose a race in. The UNIQUE constraint on
        `commitments.offer_id` is a backstop behind this, not the mechanism
        doing the actual work; it only fires if the claim above is ever wrong,
        translated to `ValueError` via `db.UniqueConstraintError` so it stays
        indistinguishable from the ordinary "already spent" case to callers.

        This is also what makes `_WRITE_LOCK` unnecessary for correctness —
        it was, before this method looked like this, the only thing standing
        between SQLite and a real double-spend under FastAPI's threadpool.

        Args:
            commitment_id: Id to assign.
            offer_id: The offer being spent.
            agent_id: Who owes the money.
            resource_id: What they bought.
            amount_paise: How much, in paise.
            asset: Currency code.
            mode: "deferred" or "per_request".
            settle_date: Batching key; defaults to today UTC.

        Returns:
            The created commitment as a dict.

        Raises:
            ValueError: If the offer is missing or already spent.
        """
        settle_date = settle_date or today_utc()
        created_at = utc_now()

        with _WRITE_LOCK, self._connect() as conn:
            claimed = conn.execute(
                "UPDATE offers SET status = 'consumed' WHERE offer_id = ? AND status = 'open'",
                (offer_id,),
            )
            if claimed.rowcount == 0:
                row = conn.execute(
                    "SELECT status FROM offers WHERE offer_id = ?", (offer_id,)
                ).fetchone()
                if row is None:
                    raise ValueError(f"offer {offer_id} does not exist")
                raise ValueError(f"offer {offer_id} is already {row['status']}")

            try:
                conn.execute(
                    "INSERT INTO commitments (commitment_id, offer_id, agent_id, resource_id,"
                    " amount_paise, asset, created_at, settle_date, mode, status)"
                    " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending')",
                    (
                        commitment_id,
                        offer_id,
                        agent_id,
                        resource_id,
                        int(amount_paise),
                        asset,
                        created_at,
                        settle_date,
                        mode,
                    ),
                )
            except db.UniqueConstraintError as exc:
                # Should be unreachable given the claim above — offer_id
                # UNIQUE is a backstop, not the primary guard. Kept because an
                # untested backstop is not really a backstop.
                raise ValueError(f"offer {offer_id} already has a commitment") from exc

        return {
            "commitmentId": commitment_id,
            "offerId": offer_id,
            "agentId": agent_id,
            "resourceId": resource_id,
            "amountPaise": int(amount_paise),
            "asset": asset,
            "createdAt": created_at,
            "settleDate": settle_date,
            "mode": mode,
            "status": "pending",
        }

    def pending_commitments(
        self, *, agent_id: str | None = None, settle_date: str | None = None
    ) -> list[Mapping[str, Any]]:
        """Lists unsettled commitments, optionally narrowed to one agent or day."""
        query = "SELECT * FROM commitments WHERE status = 'pending'"
        params: list[Any] = []
        if agent_id:
            query += " AND agent_id = ?"
            params.append(agent_id)
        if settle_date:
            query += " AND settle_date = ?"
            params.append(settle_date)
        query += " ORDER BY created_at ASC"

        with self._connect() as conn:
            return conn.execute(query, params).fetchall()

    def pending_agents(self, *, settle_date: str | None = None) -> list[str]:
        """Agent ids that currently owe something."""
        query = "SELECT DISTINCT agent_id FROM commitments WHERE status = 'pending'"
        params: list[Any] = []
        if settle_date:
            query += " AND settle_date = ?"
            params.append(settle_date)

        with self._connect() as conn:
            return [r["agent_id"] for r in conn.execute(query, params).fetchall()]

    # -- batches -----------------------------------------------------------

    def record_batch(
        self,
        *,
        batch_id: str,
        agent_id: str,
        settle_date: str,
        commitment_ids: list[str],
        total_paise: int,
        payment_link_id: str | None,
        payment_link_url: str | None,
        status: str,
        razorpay_mode: str,
        error_message: str | None = None,
    ) -> None:
        """Writes the batch and marks its commitments settled, in one transaction.

        If the Razorpay call failed, the commitments stay `pending` so the next
        run picks them up again — a failed charge must never look like a paid
        one.
        """
        with _WRITE_LOCK, self._connect() as conn:
            conn.execute(
                "INSERT INTO batches (batch_id, agent_id, settle_date, created_at,"
                " commitment_count, total_paise, payment_link_id, payment_link_url,"
                " status, razorpay_mode, error_message)"
                " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    batch_id,
                    agent_id,
                    settle_date,
                    utc_now(),
                    len(commitment_ids),
                    int(total_paise),
                    payment_link_id,
                    payment_link_url,
                    status,
                    razorpay_mode,
                    error_message,
                ),
            )

            if status == "created":
                conn.executemany(
                    "UPDATE commitments SET status = 'settled', batch_id = ?"
                    " WHERE commitment_id = ?",
                    [(batch_id, cid) for cid in commitment_ids],
                )
            elif status == "failed":
                # Leave them pending on purpose — see docstring.
                conn.executemany(
                    "UPDATE commitments SET status = 'pending' WHERE commitment_id = ?",
                    [(cid,) for cid in commitment_ids],
                )

    def get_batch(self, batch_id: str) -> Mapping[str, Any] | None:
        """Looks up one batch, or None."""
        with self._connect() as conn:
            return conn.execute(
                "SELECT * FROM batches WHERE batch_id = ?", (batch_id,)
            ).fetchone()

    def get_batch_by_link(self, payment_link_id: str) -> Mapping[str, Any] | None:
        """Finds the batch a Razorpay Payment Link belongs to.

        The lookup a webhook needs: Razorpay tells us about a `plink_...`, and
        we have to map it back to the commitments it covers.
        """
        with self._connect() as conn:
            return conn.execute(
                "SELECT * FROM batches WHERE payment_link_id = ?", (payment_link_id,)
            ).fetchone()

    # -- webhooks ----------------------------------------------------------

    def claim_webhook(
        self, *, dedupe_key: str, event: str, payment_link_id: str | None
    ) -> bool:
        """Claims a webhook delivery for processing, exactly once.

        Razorpay retries until it gets a 2xx, so redelivery is routine rather
        than exceptional — and a redelivered `payment_link.paid` that gets
        applied twice would double-count collected revenue. The guard is a
        primary-key INSERT rather than a "have we seen this?" SELECT: two
        concurrent deliveries of the same event both pass a SELECT check, and
        only one can win an INSERT.

        Args:
            dedupe_key: Stable identifier for this delivery.
            event: Razorpay event name.
            payment_link_id: The link this concerns, when there is one.

        Returns:
            True if this caller now owns the delivery, False if it was already
            processed and should be acknowledged without further action.
        """
        with _WRITE_LOCK, self._connect() as conn:
            # Same `ON CONFLICT DO NOTHING` as `register_agent`, and for the
            # same reason: a caught unique violation leaves a Postgres
            # transaction aborted, so nothing else can run on that connection
            # afterwards. Nothing does here *today*, which is the trap — the
            # next person to add a statement below this line would find it
            # failing for a reason that has nothing to do with what they wrote.
            claimed = conn.execute(
                "INSERT INTO webhook_events"
                " (dedupe_key, event, received_at, payment_link_id, outcome)"
                " VALUES (?, ?, ?, ?, 'claimed') ON CONFLICT (dedupe_key) DO NOTHING",
                (dedupe_key, event, utc_now(), payment_link_id),
            )
            return claimed.rowcount == 1

    def finish_webhook(self, *, dedupe_key: str, outcome: str, **detail: Any) -> None:
        """Records how a claimed webhook delivery turned out."""
        with _WRITE_LOCK, self._connect() as conn:
            conn.execute(
                "UPDATE webhook_events SET outcome = ?, detail = ? WHERE dedupe_key = ?",
                (
                    outcome,
                    json.dumps(detail, sort_keys=True, default=str) if detail else None,
                    dedupe_key,
                ),
            )

    def mark_batch_paid(
        self,
        *,
        payment_link_id: str,
        amount_paid_paise: int,
        razorpay_payment_id: str | None,
    ) -> Mapping[str, Any] | None:
        """Marks a batch actually paid, on confirmation from Razorpay.

        This is the only place a batch becomes `paid`. The settlement run that
        created the link deliberately does not, because creating an invoice is
        not evidence that anyone settled it.

        Conditional on the batch not already being paid, for the same reason
        `create_commitment` claims its offer conditionally — the check and the
        write have to be one statement or a concurrent redelivery slips
        between them.

        Args:
            payment_link_id: Razorpay's `plink_...` id.
            amount_paid_paise: What Razorpay says arrived, in paise.
            razorpay_payment_id: The underlying `pay_...` id, when present.

        Returns:
            The updated batch row, or None if there is no such link or it was
            already marked paid.
        """
        with _WRITE_LOCK, self._connect() as conn:
            updated = conn.execute(
                "UPDATE batches SET status = 'paid', paid_at = ?, amount_paid_paise = ?,"
                " razorpay_payment_id = ?"
                " WHERE payment_link_id = ? AND status <> 'paid'",
                (utc_now(), int(amount_paid_paise), razorpay_payment_id, payment_link_id),
            )
            if updated.rowcount == 0:
                return None
            return conn.execute(
                "SELECT * FROM batches WHERE payment_link_id = ?", (payment_link_id,)
            ).fetchone()

    def release_batch(
        self, *, payment_link_id: str, status: str
    ) -> Mapping[str, Any] | None:
        """Voids an unpaid batch and returns its commitments to the queue.

        For `payment_link.expired` and `payment_link.cancelled`: the invoice
        will never be paid, but the debt behind it is still real. Detaching
        the commitments and setting them back to `pending` puts them in front
        of the next settlement run, which re-bills them on a fresh link.

        Deliberately refuses to touch a batch that is already `paid`. An
        `expired` event can legitimately arrive after a `paid` one — Razorpay
        expires the link on schedule regardless of whether it was used — and
        acting on it would un-collect money that was genuinely received.

        Args:
            payment_link_id: Razorpay's `plink_...` id.
            status: New batch status, "expired" or "cancelled".

        Returns:
            The updated batch row, or None if there is no such link or it was
            already paid or already in this state.
        """
        with _WRITE_LOCK, self._connect() as conn:
            updated = conn.execute(
                "UPDATE batches SET status = ?"
                " WHERE payment_link_id = ? AND status NOT IN ('paid', ?)",
                (status, payment_link_id, status),
            )
            if updated.rowcount == 0:
                return None

            batch = conn.execute(
                "SELECT * FROM batches WHERE payment_link_id = ?", (payment_link_id,)
            ).fetchone()
            conn.execute(
                "UPDATE commitments SET status = 'pending', batch_id = NULL WHERE batch_id = ?",
                (batch["batch_id"],),
            )
            return batch

    # -- reporting ---------------------------------------------------------

    def revenue_below(self, amount_paise: int, settle_date: str | None = None) -> dict:
        """Revenue made up of individually-too-small charges.

        The headline number in the publisher's report: money that per-request
        settlement could not have collected at any price, because each charge
        sits under the payment gateway's floor.

        Computed from the actual commitment rows rather than inferred from
        per-agent averages. An agent that fetches both a ₹5 report and forty
        ₹0.50 API calls has a mean above the floor while forty of its
        forty-one charges are below it, so an average would understate this
        badly.

        Args:
            amount_paise: The floor to compare against.
            settle_date: Day to inspect. Defaults to today UTC.

        Returns:
            `{"count": ..., "totalPaise": ...}` for commitments under the floor.
        """
        settle_date = settle_date or today_utc()
        with self._connect() as conn:
            row = conn.execute(
                "SELECT COUNT(*) AS count, COALESCE(SUM(amount_paise), 0) AS total"
                " FROM commitments WHERE settle_date = ? AND amount_paise < ?",
                (settle_date, int(amount_paise)),
            ).fetchone()
        return {"count": row["count"], "totalPaise": row["total"]}

    def daily_summary(self, settle_date: str | None = None, agent_id: str | None = None) -> dict:
        """Aggregates one day's activity for the publisher's report.

        `agent_id` exists for the console UI: with several visitors hitting a
        shared deployment, an unfiltered summary is everyone's revenue mixed
        together, and an unfiltered `batches` list lets one visitor see (and
        via `/settle-batch`, sweep) another's pending commitments. Every
        caller that predates the console — `reporting/daily_summary.py`, the
        CI flow scripts, this method's own tests — passes no `agent_id` and
        sees exactly what they saw before.

        Args:
            settle_date: Day to summarise, YYYY-MM-DD. Defaults to today UTC.
            agent_id: Narrow to one agent. Omit for the whole day.

        Returns:
            Totals, per-agent breakdown, and the batches generated.
        """
        settle_date = settle_date or today_utc()
        agent_filter = " AND agent_id = ?" if agent_id else ""
        params: tuple = (settle_date, agent_id) if agent_id else (settle_date,)

        with self._connect() as conn:
            totals = conn.execute(
                "SELECT COUNT(*) AS requests, COALESCE(SUM(amount_paise), 0) AS total_paise"
                f" FROM commitments WHERE settle_date = ?{agent_filter}",
                params,
            ).fetchone()

            by_agent = conn.execute(
                "SELECT agent_id, COUNT(*) AS requests,"
                " COALESCE(SUM(amount_paise), 0) AS total_paise,"
                " SUM(CASE WHEN status = 'settled' THEN 1 ELSE 0 END) AS settled,"
                " SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) AS pending"
                f" FROM commitments WHERE settle_date = ?{agent_filter}"
                " GROUP BY agent_id ORDER BY total_paise DESC",
                params,
            ).fetchall()

            by_resource = conn.execute(
                "SELECT resource_id, COUNT(*) AS requests,"
                " COALESCE(SUM(amount_paise), 0) AS total_paise"
                f" FROM commitments WHERE settle_date = ?{agent_filter}"
                " GROUP BY resource_id ORDER BY total_paise DESC",
                params,
            ).fetchall()

            batches = conn.execute(
                f"SELECT * FROM batches WHERE settle_date = ?{agent_filter}"
                " ORDER BY created_at ASC",
                params,
            ).fetchall()

            rejections = conn.execute(
                "SELECT COUNT(*) AS n FROM events"
                f" WHERE status = 'rejected' AND substr(ts, 1, 10) = ?{agent_filter}",
                params,
            ).fetchone()

            # Money Razorpay has actually confirmed, as distinct from money
            # that has been billed. Reads `amount_paid_paise` — what the
            # webhook reported arriving — rather than the batch total, so a
            # partial payment is not rounded up into a full one.
            collected = conn.execute(
                "SELECT COALESCE(SUM(amount_paid_paise), 0) AS collected,"
                " COUNT(*) AS paid_batches"
                f" FROM batches WHERE status = 'paid' AND settle_date = ?{agent_filter}",
                params,
            ).fetchone()

        return {
            "settleDate": settle_date,
            "agentId": agent_id,
            "requests": totals["requests"],
            "totalPaise": totals["total_paise"],
            # Explicit aliases for the two questions `totalPaise` alone is
            # ambiguous about. See the module docstring: billed is not banked.
            "committedPaise": totals["total_paise"],
            "collectedPaise": collected["collected"],
            "paidBatches": collected["paid_batches"],
            "rejectedPayments": rejections["n"],
            "byAgent": [dict(r) for r in by_agent],
            "byResource": [dict(r) for r in by_resource],
            "batches": [dict(r) for r in batches],
        }

    def commitment_amounts(
        self, *, agent_id: str | None = None, settle_date: str | None = None
    ) -> list[int]:
        """All commitment amounts for a day, regardless of status.

        Feeds `estimate_settlement_cost` for a *read-only* economics view.
        `/settle-batch` computes the same comparison but only ever sees
        commitments still `pending` — so a read built the same way would go
        blank the instant a batch clears, which is a strange way for a
        dashboard card to behave. This counts the whole day's traffic, settled
        or not.

        Args:
            agent_id: Narrow to one agent. Omit for every agent that day.
            settle_date: Day to inspect. Defaults to today UTC.

        Returns:
            One entry per commitment, in paise.
        """
        settle_date = settle_date or today_utc()
        query = "SELECT amount_paise FROM commitments WHERE settle_date = ?"
        params: list[Any] = [settle_date]
        if agent_id:
            query += " AND agent_id = ?"
            params.append(agent_id)

        with self._connect() as conn:
            return [int(r["amount_paise"]) for r in conn.execute(query, params).fetchall()]

    def list_events(
        self,
        *,
        agent_id: str | None = None,
        limit: int = 50,
        since_id: int | None = None,
    ) -> list[dict]:
        """Recent audit-log rows, newest first — the live feed for the console.

        `detail` is stored as a JSON string (see `log_event`); parsed back into
        an object here so a caller gets a normal value rather than a string to
        parse itself.

        Args:
            agent_id: Narrow to one agent's events.
            limit: Row cap, clamped to [1, 200] regardless of what is asked for
                — this is a public-facing read in the console's case, and
                nothing should be able to ask for the whole table in one call.
            since_id: Only rows with `id` greater than this. Lets a poller ask
                for "what's new" instead of re-fetching everything.

        Returns:
            Rows as camelCase dicts, `detail` already parsed.
        """
        query = (
            "SELECT id, ts, event, agent_id, resource_id, amount_paise, status, detail"
            " FROM events"
        )
        clauses: list[str] = []
        params: list[Any] = []
        if agent_id:
            clauses.append("agent_id = ?")
            params.append(agent_id)
        if since_id is not None:
            clauses.append("id > ?")
            params.append(since_id)
        if clauses:
            query += " WHERE " + " AND ".join(clauses)
        query += " ORDER BY id DESC LIMIT ?"
        params.append(max(1, min(int(limit), 200)))

        with self._connect() as conn:
            rows = conn.execute(query, params).fetchall()

        return [
            {
                "id": row["id"],
                "ts": row["ts"],
                "event": row["event"],
                "agentId": row["agent_id"],
                "resourceId": row["resource_id"],
                "amountPaise": row["amount_paise"],
                "status": row["status"],
                "detail": json.loads(row["detail"]) if row["detail"] else {},
            }
            for row in rows
        ]
