-- Bharat x402 — Postgres schema, initial migration.
--
-- Apply this once, by hand, in the Supabase SQL editor (or `psql`) before
-- pointing LEDGER_DSN at a Postgres database. It is not applied automatically
-- on startup — see the docstring on Ledger.__init__ in facilitator/ledger.py
-- for why: schema changes on a shared production database belong in a
-- migration run deliberately, not as a side effect of the facilitator
-- importing on a cold start.
--
-- (The one exception is CI, which sets LEDGER_AUTO_MIGRATE=1 to bootstrap a
-- throwaway postgres:16 service container that starts genuinely empty and
-- has no one to run this by hand.)
--
-- THIS FILE IS GENERATED, NOT HAND-MAINTAINED. It is the literal output of
-- `ledger.schema_sql("postgres")` — the same function that builds the SQLite
-- schema, so there is exactly one definition of the schema in the codebase,
-- not two that can quietly drift apart. If ledger.py's schema_sql changes,
-- regenerate this file rather than hand-editing it:
--
--   python -c "import sys; sys.path.insert(0, 'facilitator'); \
--     from ledger import schema_sql; print(schema_sql('postgres'))" \
--     > facilitator/migrations/001_init.sql
--   (then restore this header comment above the generated SQL)


-- One row per agent that has registered a signing key. Holds only the
-- *public* half: the facilitator can verify an agent's commitments and can
-- never produce one, which is the entire point of moving off a shared HMAC
-- secret (see payment_verifier.py).
CREATE TABLE IF NOT EXISTS agents (
    agent_id      TEXT PRIMARY KEY,
    -- base64 of the raw 32-byte Ed25519 public key.
    public_key    TEXT NOT NULL,
    algorithm     TEXT NOT NULL,
    registered_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS offers (
    offer_id      TEXT PRIMARY KEY,
    agent_id      TEXT NOT NULL,
    resource_id   TEXT NOT NULL,
    resource_url  TEXT,
    amount_paise  INTEGER NOT NULL,
    asset         TEXT NOT NULL,
    scheme        TEXT NOT NULL,
    network       TEXT NOT NULL,
    pay_to        TEXT NOT NULL,
    nonce         TEXT NOT NULL,
    signature     TEXT NOT NULL,
    issued_at     TEXT NOT NULL,
    expires_at    TEXT NOT NULL,
    -- open: quoted, not yet spent. consumed: turned into a commitment.
    status        TEXT NOT NULL DEFAULT 'open'
);

CREATE TABLE IF NOT EXISTS batches (
    batch_id            TEXT PRIMARY KEY,
    agent_id            TEXT NOT NULL,
    settle_date         TEXT NOT NULL,
    created_at          TEXT NOT NULL,
    commitment_count    INTEGER NOT NULL,
    total_paise         INTEGER NOT NULL,
    -- What Razorpay gave us back. Null in dry-run.
    payment_link_id     TEXT,
    payment_link_url    TEXT,
    -- created | paid | expired | cancelled | failed | dry_run
    --
    -- `created` means an invoice exists, NOT that money arrived. Only the
    -- signed Razorpay webhook moves a batch to `paid` (see webhooks.py).
    status              TEXT NOT NULL,
    razorpay_mode       TEXT NOT NULL,
    error_message       TEXT,
    -- Filled in by the webhook, not by the settlement run that created the
    -- link. Null until Razorpay confirms payment.
    paid_at             TEXT,
    amount_paid_paise   INTEGER,
    razorpay_payment_id TEXT
);

CREATE TABLE IF NOT EXISTS commitments (
    commitment_id TEXT PRIMARY KEY,
    -- One commitment per offer, enforced by the database rather than by
    -- application logic. This is what makes double-charging structurally
    -- impossible rather than merely unlikely.
    offer_id      TEXT NOT NULL UNIQUE,
    agent_id      TEXT NOT NULL,
    resource_id   TEXT NOT NULL,
    amount_paise  INTEGER NOT NULL,
    asset         TEXT NOT NULL,
    created_at    TEXT NOT NULL,
    settle_date   TEXT NOT NULL,
    -- deferred: awaiting batch. per_request: charged immediately.
    mode          TEXT NOT NULL,
    -- pending | settled | failed
    status        TEXT NOT NULL DEFAULT 'pending',
    batch_id      TEXT,
    FOREIGN KEY (offer_id) REFERENCES offers (offer_id),
    FOREIGN KEY (batch_id) REFERENCES batches (batch_id)
);

-- Append-only. Nothing in this table is ever updated or deleted; it is the
-- audit trail you would hand an auditor or replay to reconstruct a day.
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts           TEXT NOT NULL,
    event        TEXT NOT NULL,
    agent_id     TEXT,
    resource_id  TEXT,
    amount_paise INTEGER,
    status       TEXT,
    detail       TEXT
);

-- Razorpay retries a webhook until it gets a 2xx, so the same event will
-- arrive more than once as a matter of course — not as an edge case. The
-- primary key is the dedupe guard: processing claims the key with an INSERT
-- first, and a duplicate delivery loses that INSERT and returns early
-- without touching a batch. Same discipline as `commitments.offer_id`:
-- exactly-once is enforced by a database constraint, not by application
-- logic remembering to check.
CREATE TABLE IF NOT EXISTS webhook_events (
    dedupe_key      TEXT PRIMARY KEY,
    event           TEXT NOT NULL,
    received_at     TEXT NOT NULL,
    payment_link_id TEXT,
    -- claimed | applied | ignored | unknown_link
    outcome         TEXT NOT NULL,
    detail          TEXT
);

CREATE INDEX IF NOT EXISTS idx_commitments_settlement
    ON commitments (status, agent_id, settle_date);
CREATE INDEX IF NOT EXISTS idx_events_ts ON events (ts);
CREATE INDEX IF NOT EXISTS idx_batches_payment_link ON batches (payment_link_id);

